name: C/C++ CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ./configure
        run: ./configure

      - name: Make
        run: make

      - name: Run check
        run: make check

      - name: Run distcheck
        run: make distcheck

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build Dockerfile image
        run: docker build --platform=linux/amd64 -t alekstikhonov/classaserver --push .
