name: C/C++ CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ./configure
        run: ./configure

      - name: Make
        run: make

      - name: Run check
        run: make check

      - name: Run distcheck
        run: make distcheck

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build Dockerfile image
        run: docker build --platform=linux/amd64 -t alekstikhonov/classaserver --push .
