name: C/C++ CI

on:
  push:
    branches:
      - branchAutomake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install -y automake autoconf libtool g++

      - name: Generate Build Scripts
        run: |
          aclocal
          autoconf
          automake --add-missing

      - name: Configure and Build
        run: ./configure && make

      - name: Create Tarball
        run: make dist

      - name: Upload Tarball
        uses: actions/upload-artifact@v4
        with:
          name: classa-tarball
          path: classa-*.tar.gz
