name: C/C++ CI - Build Debian Package

on:
  push:
    branches:
      - branchAutoPackage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential devscripts

      - name: Generate Build Scripts
        run: |
          aclocal
          autoconf
          automake --add-missing

      - name: Configure and Build
        run: ./configure && make

      - name: Build Debian Package
        run: dpkg-deb --build deb

      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: deb
