name: Docker Multi-Architecture

on:
  push:
    branches:
      ["*"]

jobs:
  build-and-push:
    name: Build and Push Docker Images for amd64 and arm64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: alekstikhonov/classaserver:latest
          platforms: linux/amd64,linux/arm64
          provenance: false

      - name: Create and Push Multi-Arch Manifest
        run: |
          docker buildx imagetools create -t alekstikhonov/classaserver:latest \
          alekstikhonov/classaserver:latest
